name: Zig CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "get_me_ports/**"
      - ".github/workflows/get-me-ports.yml"
  release:
    types: [ "published" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig fmt --check get_me_ports/main.zig
              