name: Zig CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "get_me_ports/**"
      - ".github/workflows/get-me-ports.yml"
  release:
    types: [ "published" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig build-exe get_me_ports/main.zig -fstrip -fsingle-threaded -target x86_64-linux -O ReleaseSafe
  
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: main
          path: .

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: main
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.head_ref || github.ref_name }}
          releaseName: ${{ github.head_ref || github.ref_name }}
          releaseNotes: ${{ github.event.release.body }}
          overwrite: true
              